title: Yang Zhou's Homepage
page-top-title: Yang Zhou
top-section-bg-text: Mechanical Engineering
home-subtitle: Yang Zhou&ensp;|&ensp;周阳
copyright-text: '&copy; Yang Zhou 2023-2026. All Rights Reserved.'
